---
- name: Install monitoring and security tools
  ansible.builtin.apt:
    name:
      - htop
      - iotop
      - nethogs
      - logwatch
      - auditd
      - aide
    state: present
    update_cache: true
  become: true

- name: Create monitoring directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - /opt/monitoring
    - /opt/security
    - /var/log/security
  become: true

- name: Configure security event logging
  ansible.builtin.template:
    src: security-events.conf.j2
    dest: /etc/rsyslog.d/security-events.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart rsyslog

- name: Configure log integrity monitoring
  ansible.builtin.template:
    src: log-monitor.sh.j2
    dest: /opt/security/log-monitor.sh
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Configure AIDE for file integrity monitoring
  ansible.builtin.template:
    src: aide.conf.j2
    dest: /etc/aide/aide.conf
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Initialize AIDE database
  ansible.builtin.command: aideinit
  become: true
  changed_when: false

- name: Configure auditd for system monitoring
  ansible.builtin.template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart auditd

- name: Configure audit rules
  ansible.builtin.template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart auditd

- name: Create security monitoring cron jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    job: "{{ item.job }}"
    user: root
  loop:
    - {
        name: "Security Log Analysis",
        hour: "1",
        minute: "0",
        job: "/opt/security/log-monitor.sh",
      }
    - {
        name: "File Integrity Check",
        hour: "3",
        minute: "0",
        job: "aide --check",
      }
    - {
        name: "System Health Check",
        hour: "*/6",
        minute: "0",
        job: "/opt/monitoring/health-check.sh",
      }
  become: true

- name: Configure log rotation for security logs
  ansible.builtin.template:
    src: security-logs.j2
    dest: /etc/logrotate.d/security-logs
    owner: root
    group: root
    mode: "0644"
  become: true
