---
- name: Check if Docker is running
  ansible.builtin.command: docker info
  register: docker_info
  changed_when: false
  failed_when: false
  become: true

- name: Fail if Docker is not running
  ansible.builtin.fail:
    msg: "Docker is not running. Please install and start Docker first."
  when: docker_info.rc != 0

# Get list of all networks (for removal operations)
- name: Get existing Docker networks
  ansible.builtin.command: >-
    docker network ls --format "{{ '{{' }}.Name{{ '}}' }}"
  register: existing_networks
  changed_when: false
  become: true

# Remove project-specific networks
- name: Remove project Docker networks
  community.docker.docker_network:
    name: "{{ item }}"
    state: absent
  loop:
    - "test-to-delete-web-network"
    - "test-db-network"
    - "test-to-delete-monitoring-network"
    - "test-api-network"
    - "test-cache-network"
  become: true
  failed_when: false

# Optional: Remove ALL custom networks (use with caution)
- name: Remove all custom Docker networks
  community.docker.docker_network:
    name: "{{ item }}"
    state: absent
  loop: >-
    {{
      existing_networks.stdout_lines |
      select('match', '^(?!bridge|host|none).*$') |
      list
    }}
  become: true
  failed_when: false
  when: features.containers.networks.remove_all

- name: Debug network removal
  ansible.builtin.debug:
    msg: >-
      Removed {{
        existing_networks.stdout_lines |
        select('match', '^(?!bridge|host|none).*$') |
        list | length
      }} custom networks
  when: features.containers.networks.remove_all

# Prune unused networks
- name: Prune unused Docker networks
  ansible.builtin.command: docker network prune -f
  become: true
  changed_when: false

# Create default networks (only for testing/validation)
- name: Create default Docker networks for testing
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: >-
      {{
        item.driver |
        default(configure_docker_networks_default_driver)
      }}
    ipam_config:
      - subnet: "{{ item.subnet }}"
    state: present
    labels:
      description: "{{ item.description }}"
      environment: "{{ configure_docker_networks_labels.environment }}"
      managed_by: "{{ configure_docker_networks_labels.managed_by }}"
  loop: "{{ features.containers.networks.default_networks }}"
  become: true
  when: features.containers.networks.test_mode

# Create custom networks if defined (only for testing/validation)
- name: Create custom Docker networks for testing
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: >-
      {{
        item.driver |
        default(configure_docker_networks_default_driver)
      }}
    ipam_config:
      - subnet: "{{ item.subnet }}"
    state: present
    labels:
      description: "{{ item.description }}"
      environment: "{{ configure_docker_networks_labels.environment }}"
      managed_by: "{{ configure_docker_networks_labels.managed_by }}"
  loop: "{{ features.containers.networks.custom_networks }}"
  become: true
  when: >-
    features.containers.networks.test_mode and
    features.containers.networks.custom_networks | length > 0

# Display network information (only in test mode)
- name: List Docker networks
  ansible.builtin.command: >-
    docker network ls --format
    "table {{ '{{' }}.Name{{ '}}' }}\t{{ '{{' }}.Driver{{ '}}' }}\t{{ '{{' }}.Scope{{ '}}' }}"
  register: docker_networks
  changed_when: false
  become: true
  when: features.containers.networks.test_mode

- name: Debug Docker networks
  ansible.builtin.debug:
    msg: "{{ docker_networks.stdout_lines }}"
  when: features.containers.networks.test_mode

# Verify network connectivity (only in test mode)
- name: Test network connectivity
  ansible.builtin.command: >-
    docker run --rm --network test-to-delete-web-network
    alpine ping -c 1 8.8.8.8
  register: network_test
  changed_when: false
  failed_when: false
  become: true
  when: features.containers.networks.test_mode

- name: Debug network connectivity test
  ansible.builtin.debug:
    msg: >-
      Network connectivity test: {{
        'PASSED' if network_test.rc == 0 else 'FAILED'
      }}
  when: features.containers.networks.test_mode

# Cleanup: Remove all created networks after testing
- name: Remove all created networks after testing
  community.docker.docker_network:
    name: "{{ item.name }}"
    state: absent
  loop: >-
    {{
      features.containers.networks.default_networks +
      features.containers.networks.custom_networks
    }}
  become: true
  failed_when: false
  when: features.containers.networks.test_mode

- name: Final network cleanup
  ansible.builtin.command: docker network prune -f
  become: true
  changed_when: false
  when: features.containers.networks.test_mode

- name: Debug final cleanup
  ansible.builtin.debug:
    msg: "All test networks have been removed. No predefined networks remain."
  when: features.containers.networks.test_mode
