---
# Simplified reporting configuration - remove complex variable references
configure_reporting_enabled: true
configure_reporting_daily_enabled: true
configure_reporting_weekly_enabled: true
configure_reporting_monthly_enabled: true

# Use simple defaults instead of complex variable references
configure_reporting_daily_hour: "6"
configure_reporting_daily_minute: "0"
configure_reporting_weekly_day: "0"
configure_reporting_weekly_hour: "7"
configure_reporting_weekly_minute: "0"
configure_reporting_monthly_day: "1"
configure_reporting_monthly_hour: "8"
configure_reporting_monthly_minute: "0"

# Storage and performance (keep these)
configure_reporting_storage_dir: "/opt/reports"
configure_reporting_archive_dir: "/opt/reports/archive"
configure_reporting_critical_threshold: 3
configure_reporting_high_threshold: 10
configure_reporting_memory_limit: "256M"
configure_reporting_timeout: 300
configure_reporting_max_log_size: "5M"
