---
- name: Simple test task
  ansible.builtin.debug:
    msg: "Role is working!"

- name: Show test mode value
  ansible.builtin.debug:
    msg: "Test mode is: {{ features.containers.networks.test_mode }}"
