---
# Pre-test validation
- name: Check if Docker is running
  ansible.builtin.command: docker info
  register: docker_info
  changed_when: false
  failed_when: false

- name: Fail if Docker is not running
  ansible.builtin.fail:
    msg: "Docker is not running. Cannot perform network security tests."
  when: docker_info.rc != 0

- name: Check if UFW is enabled
  ansible.builtin.command: ufw status
  register: ufw_status
  changed_when: false
  failed_when: false

- name: Fail if UFW is not enabled
  ansible.builtin.fail:
    msg: "UFW is not enabled. Cannot perform firewall security tests."
  when: "'Status: active' not in ufw_status.stdout"

# Test 1: Firewall Configuration Validation
- name: Test 1.1 - Validate UFW default policies
  ansible.builtin.command: ufw status verbose
  register: ufw_verbose_status
  changed_when: false

- name: Validate default deny incoming policy
  ansible.builtin.assert:
    that:
      - ufw_verbose_status.stdout is search("Default: deny (incoming)")
    fail_msg: "UFW default incoming policy is not set to deny"
    success_msg: "✓ UFW default incoming policy is correctly set to deny"

- name: Validate default allow outgoing policy
  ansible.builtin.assert:
    that:
      - ufw_verbose_status.stdout is search("Default: allow (outgoing)")
    fail_msg: "UFW default outgoing policy is not set to allow"
    success_msg: "✓ UFW default outgoing policy is correctly set to allow"

- name: Test 1.2 - Validate SSH access
  ansible.builtin.assert:
    that:
      - ufw_verbose_status.stdout is search("22")
    fail_msg: "SSH port 22 is not allowed in firewall"
    success_msg: "✓ SSH port 22 is correctly allowed"

- name: Test 1.3 - Validate HTTP/HTTPS access
  ansible.builtin.assert:
    that:
      - ufw_verbose_status.stdout is search("80")
      - ufw_verbose_status.stdout is search("443")
    fail_msg: "HTTP/HTTPS ports are not allowed in firewall"
    success_msg: "✓ HTTP/HTTPS ports are correctly allowed"

- name: Test 1.4 - Validate Docker network restrictions
  ansible.builtin.command: ufw status numbered
  register: ufw_numbered_status
  changed_when: false

- name: Check for broad Docker network ranges (should NOT exist)
  ansible.builtin.assert:
    that:
      - ufw_numbered_status.stdout is not search("172.16.0.0/12")
      - ufw_numbered_status.stdout is not search("192.168.0.0/16")
      - ufw_numbered_status.stdout is not search("10.0.0.0/8")
    fail_msg: "Broad Docker network ranges are still allowed (security issue)"
    success_msg: "✓ Broad Docker network ranges are correctly blocked"

- name: Check for specific Docker network ranges (should exist)
  ansible.builtin.assert:
    that:
      - ufw_numbered_status.stdout is search(item)
    fail_msg: "Docker network range {{ item }} is not allowed in firewall"
    success_msg: "✓ Docker network range {{ item }} is correctly allowed"
  loop: "{{ configure_firewall_docker_networks }}"

# Test 2: Docker Network Validation
- name: Test 2.1 - List Docker networks
  ansible.builtin.command: docker network ls --format "{{ '{{' }}.Name{{ '}}' }}"
  register: docker_networks
  changed_when: false

- name: Validate required networks exist
  ansible.builtin.assert:
    that:
      - docker_networks.stdout is search("web-network")
      - docker_networks.stdout is search("db-network")
      - docker_networks.stdout is search("monitoring-network")
    fail_msg: "Required Docker networks are not created"
    success_msg: "✓ All required Docker networks are created"

# Test 2.2 - Validate network configurations (simplified)
- name: Validate network configurations
  ansible.builtin.command: docker network inspect {{ item.name }} --format "{{ '{{' }}.IPAM.Config{{ '}}' }}"
  register: network_inspections
  loop: "{{ test_network_security_expected_networks }}"
  changed_when: false

- name: Validate network subnet configurations (simplified)
  ansible.builtin.assert:
    that:
      - "item.item.subnet in item.stdout"
    fail_msg: "Network {{ item.item.name }} has incorrect subnet configuration"
    success_msg: "✓ Network {{ item.item.name }} has correct subnet configuration"
  loop: "{{ network_inspections.results }}"
  when: network_inspections.results is defined

# Test 3: Container Network Isolation
- name: Test 3.1 - Create test containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    networks:
      - name: "{{ item.network }}"
    command: "{{ item.command }}"
    labels:
      test: "true"
      service: "{{ item.service }}"
    state: started
    detach: true
  loop: "{{ test_network_security_test_containers }}"
  become: true

- name: Test 3.2 - Verify container network assignment
  ansible.builtin.command: docker inspect {{ item.name }} --format "{{ '{{' }}.NetworkSettings.Networks{{ '}}' }}"
  register: container_networks
  loop: "{{ test_network_security_test_containers }}"
  changed_when: false

- name: Validate container network assignment
  ansible.builtin.assert:
    that:
      - item.stdout is search(item.item.network)
    fail_msg: "Container {{ item.item.name }} is not on the correct network"
    success_msg: "✓ Container {{ item.item.name }} is correctly assigned to {{ item.item.network }}"
  loop: "{{ container_networks.results }}"

- name: Test 3.3 - Test cross-network communication (should fail)
  ansible.builtin.command: docker exec test-web ping -c 1 test-db
  register: cross_network_test
  changed_when: false
  failed_when: false

- name: Validate network isolation (cross-network communication should fail)
  ansible.builtin.assert:
    that:
      - cross_network_test.rc != 0
    fail_msg: "Network isolation failed - containers can communicate across networks"
    success_msg: "✓ Network isolation working - containers cannot communicate across networks"

- name: Test 3.4 - Test same-network communication (should succeed)
  ansible.builtin.command: docker exec test-web ping -c 1 8.8.8.8
  register: same_network_test
  changed_when: false
  failed_when: false

- name: Validate same-network communication
  ansible.builtin.assert:
    that:
      - same_network_test.rc == 0
    fail_msg: "Same network communication failed"
    success_msg: "✓ Same network communication working correctly"

# Test 4: Security Logging Validation
- name: Test 4.1 - Check UFW logging configuration
  ansible.builtin.command: ufw status verbose | grep -i logging
  register: ufw_logging
  changed_when: false
  failed_when: false

- name: Validate UFW logging is enabled
  ansible.builtin.assert:
    that:
      - ufw_logging.stdout != ""
    fail_msg: "UFW logging is not configured"
    success_msg: "✓ UFW logging is properly configured"

- name: Test 4.2 - Check network log directory
  ansible.builtin.stat:
    path: /var/log/network
  register: network_log_dir

- name: Validate network log directory exists
  ansible.builtin.assert:
    that:
      - network_log_dir.stat.exists
    fail_msg: "Network log directory does not exist"
    success_msg: "✓ Network log directory exists"

- name: Test 4.3 - Check logrotate configuration
  ansible.builtin.stat:
    path: /etc/logrotate.d/network
  register: network_logrotate

- name: Validate logrotate configuration exists
  ansible.builtin.assert:
    that:
      - network_logrotate.stat.exists
    fail_msg: "Network logrotate configuration does not exist"
    success_msg: "✓ Network logrotate configuration exists"

# Test 5: Performance and Security Validation
- name: Test 5.1 - Check Docker daemon configuration
  ansible.builtin.stat:
    path: /etc/docker/daemon.json
  register: docker_daemon_config

- name: Validate Docker daemon configuration exists
  ansible.builtin.assert:
    that:
      - docker_daemon_config.stat.exists
    fail_msg: "Docker daemon configuration does not exist"
    success_msg: "✓ Docker daemon configuration exists"

- name: Test 5.2 - Validate Docker daemon security settings
  ansible.builtin.command: cat /etc/docker/daemon.json
  register: docker_daemon_content
  changed_when: false

- name: Check for security settings in Docker daemon
  ansible.builtin.assert:
    that:
      - docker_daemon_content.stdout is search("iptables")
      - docker_daemon_content.stdout is search("ip-forward")
    fail_msg: "Docker daemon security settings are not configured"
    success_msg: "✓ Docker daemon security settings are properly configured"

# Cleanup test containers
- name: Cleanup test containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    state: absent
  loop: "{{ test_network_security_test_containers }}"
  become: true
  failed_when: false

# Create configurable test script
- name: Create configurable network security test script
  ansible.builtin.template:
    src: test_network_security.sh.j2
    dest: /opt/security-updates/test_network_security.sh
    mode: "0755"
    owner: root
    group: root
  become: true

# Final test summary
- name: Display test summary
  ansible.builtin.debug:
    msg: |
      ========================================
      NETWORK SECURITY TEST SUMMARY
      ========================================

      ✓ Firewall Configuration Tests
        - UFW default policies validated
        - SSH/HTTP/HTTPS access confirmed
        - Broad network ranges blocked
        - Specific network ranges allowed

      ✓ Docker Network Tests
        - Required networks created
        - Network configurations validated
        - Subnet assignments correct

      ✓ Network Isolation Tests
        - Container network assignment verified
        - Cross-network communication blocked
        - Same-network communication allowed

      ✓ Security Logging Tests
        - UFW logging enabled
        - Network log directory exists
        - Logrotate configuration present

      ✓ Docker Security Tests
        - Daemon configuration exists
        - Security settings applied
        - Network security features enabled

      All network security tests completed successfully!
      ========================================
