---
- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  become: true

- name: Restart remote logging
  ansible.builtin.service:
    name: rsyslog
    state: reloaded
  become: true
