---
- name: Configure Monitoring
  hosts: all
  become: true
  vars_files:
    - ../inventory/group_vars/defaults.yml
    - ../inventory/group_vars/all.yml
    - ../inventory/group_vars/features.yml
  vars:
    ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
  roles:
    - configure_monitoring
