---
- name: Configure log rotation for disk space management
  hosts: all
  become: true
  remote_user: "{{ initial_deployment_user }}"
  vars:
    ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
  roles:
    - configure_log_rotation
