---
- name: Configure basic system monitoring
  hosts: all
  become: true
  remote_user: "{{ initial_deployment_user }}"
  vars:
    ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
  roles:
    - configure_monitoring
