---
- name: Disable password authentication and secure SSH
  hosts: all
  become: true
  remote_user: "{{ initial_deployment_user }}"
  vars:
    ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
  roles:
    - disable_password_authentication
