---
- name: Download Logs Securely
  hosts: all
  become: true
  vars_files:
    - ../inventory/group_vars/defaults.yml
    - ../inventory/group_vars/all.yml
    - ../inventory/group_vars/features.yml
  vars:
    ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
  tasks:
    - name: Create logs directory in home
      ansible.builtin.file:
        path: ~/ansible-logs/vps
        state: directory
        mode: "0755"
      delegate_to: localhost

    - name: Download system logs
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: "~/ansible-logs/vps/system/"
        flat: true
      loop:
        - /var/log/syslog
        - /var/log/auth.log
        - /var/log/dpkg.log
      failed_when: false
      when: download_logs_secure_include_system_logs

    - name: Download monitoring logs
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: "~/ansible-logs/vps/monitoring/"
        flat: true
      loop:
        - /opt/monitoring/health-check-lightweight.sh
        - /var/log/monitoring/
      failed_when: false
      when: download_logs_secure_include_docker_logs

    - name: Download security logs
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: "~/ansible-logs/vps/security/"
        flat: true
      loop:
        - /opt/security/
        - /var/log/security/
      failed_when: false
      when: download_logs_secure_include_security_logs

    - name: Display download summary
      ansible.builtin.debug:
        msg: "Logs downloaded to ~/ansible-logs/vps/"
      delegate_to: localhost
