---
- name: Download Logs Securely
  hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
  tasks:
    - name: Create logs directory
      ansible.builtin.file:
        path: "./logs/{{ inventory_hostname }}"
        state: directory
        mode: "0755"
      delegate_to: localhost

    - name: Download system logs
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: "./logs/{{ inventory_hostname }}/"
        flat: false
      loop:
        - /var/log/syslog
        - /var/log/auth.log
        - /var/log/ufw.log
        - /var/log/fail2ban.log
        - /var/log/docker.log
        - /var/log/health-monitor.log
        - /var/log/security/security-events.log
      ignore_errors: true

    - name: Download monitoring logs
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: "./logs/{{ inventory_hostname }}/monitoring/"
        flat: false
      loop:
        - /opt/monitoring/health-check-lightweight.sh
        - /opt/monitoring/resource-monitor.sh
        - /opt/monitoring/container-monitor.sh
      ignore_errors: true

    - name: Download security logs
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: "./logs/{{ inventory_hostname }}/security/"
        flat: false
      loop:
        - /opt/security/container-scan.sh
        - /opt/security/container-security-dashboard.sh
        - /opt/security/trivy-reports/
      ignore_errors: true

    - name: Display download summary
      ansible.builtin.debug:
        msg: "Logs downloaded to ./logs/{{ inventory_hostname }}/"
      delegate_to: localhost
