---
- name: Load centralized configuration
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load defaults.yml (non-confidential defaults)
      ansible.builtin.include_vars: ../inventory/group_vars/defaults.yml

    - name: Load all.yml (environment-specific values)
      ansible.builtin.include_vars: ../inventory/group_vars/all.yml

    - name: Load features.yml (behavior configuration)
      ansible.builtin.include_vars: ../inventory/group_vars/features.yml

- name: Deploy complete system
  hosts: all
  become: true
  vars_files:
    - ../inventory/group_vars/defaults.yml
    - ../inventory/group_vars/all.yml
    - ../inventory/group_vars/features.yml
  roles:
    - update_ubuntu
    - disable_password_authentication
    - create_deployment_user
    - deploy_docker
    - configure_firewall
    - configure_security_updates
    - configure_monitoring
    - configure_reporting
    - configure_container_security
    - configure_remote_logging
    - configure_log_download
    - configure_log_rotation
    - test_network_security
    - configure_docker_networks
    - configure_fail2ban

- name: Deployment completion notification
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Send deployment completion notification
      ansible.builtin.debug:
        msg: "Deployment completed successfully at {{ ansible_date_time.iso8601 }}"
