---
- name: Pre-flight System Check
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Find all handler files using find module
      ansible.builtin.find:
        paths: "roles"
        patterns: "main.yml"
        recurse: true
        file_type: file
      register: all_files

    - name: Filter handler files
      ansible.builtin.set_fact:
        handler_files: "{{ all_files.files | selectattr('path', 'match', '.*/handlers/main\\.yml$') | list }}"

    - name: Display handler files found
      ansible.builtin.debug:
        msg: "Handler files found: {{ handler_files | map(attribute='path') | list }}"

    - name: Validate handler syntax
      ansible.builtin.command: ansible-lint "{{ item.path }}"
      loop: "{{ handler_files }}"
      register: handler_lint
      failed_when: false
      changed_when: false

    - name: Display validation results
      ansible.builtin.debug:
        msg: "Handler validation completed - Found {{ handler_files | length }} handler files"
