---
- name: Reboot Server
  hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
  tasks:
    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
