---
- name: Show Docker network information
  hosts: all
  become: false
  remote_user: "{{ containers_deployment_user }}"
  vars:
    ansible_ssh_private_key_file: "{{ containers_deployment_user_ssh_key }}"
    ansible_ssh_common_args: "-o IdentitiesOnly=yes -o PreferredAuthentications=publickey"
    ansible_user: "{{ containers_deployment_user }}"

  tasks:
    - name: Get current firewall rules for Docker networks
      ansible.builtin.command: sudo ufw status | grep "172\."
      register: firewall_rules
      changed_when: false

    - name: Display current firewall rules
      ansible.builtin.debug:
        msg: "{{ firewall_rules.stdout_lines }}"

    - name: Show available ranges
      ansible.builtin.debug:
        msg: |
          Available ranges for new projects:
          - 172.23.0.0/16
          - 172.24.0.0/16
          - 172.25.0.0/16
          - 172.26.0.0/16
          - 172.27.0.0/16
          - 172.28.0.0/16
          - 172.29.0.0/16
          - 172.30.0.0/16
          - 172.31.0.0/16

    - name: Show usage instructions
      ansible.builtin.debug:
        msg: |
          Usage:
          1. Choose an available range
          2. Create network: docker network create --subnet=RANGE my-network
          3. Add firewall rule: sudo ufw allow from RANGE
          4. Verify: sudo ufw status verbose

    - name: Get Docker networks
      ansible.builtin.command: docker network ls
      register: docker_networks
      changed_when: false

    - name: Display Docker networks
      ansible.builtin.debug:
        msg: "{{ docker_networks.stdout_lines }}"
