---
- name: Show Network Information
  hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
  tasks:
    - name: Get network interfaces
      ansible.builtin.command: ip addr show
      register: network_interfaces
      changed_when: false

    - name: Display network interfaces
      ansible.builtin.debug:
        msg: "{{ network_interfaces.stdout_lines }}"

    - name: Get UFW status
      ansible.builtin.command: ufw status verbose
      register: ufw_status
      changed_when: false

    - name: Display UFW status
      ansible.builtin.debug:
        msg: "{{ ufw_status.stdout_lines }}"

    - name: Get Docker networks
      ansible.builtin.command: docker network ls
      register: docker_networks
      changed_when: false

    - name: Display Docker networks
      ansible.builtin.debug:
        msg: "{{ docker_networks.stdout_lines }}"

    - name: Get Docker network details
      ansible.builtin.command: docker network inspect bridge
      register: bridge_network
      changed_when: false

    - name: Display bridge network details
      ansible.builtin.debug:
        msg: "{{ bridge_network.stdout_lines }}"
