---
- name: Test System Handlers
  hosts: all
  become: true
  vars_files:
    - ../inventory/group_vars/defaults.yml
    - ../inventory/group_vars/all.yml
    - ../inventory/group_vars/features.yml
  vars:
    ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
  tasks:
    - name: Test Docker service restart
      ansible.builtin.service:
        name: docker
        state: restarted
      become: true

    - name: Test UFW service restart
      ansible.builtin.service:
        name: ufw
        state: restarted
      become: true

    - name: Test Fail2ban service restart
      ansible.builtin.service:
        name: fail2ban
        state: restarted
      become: true

    - name: Display service status
      ansible.builtin.service_facts:
      become: true

    - name: Show Docker status
      ansible.builtin.debug:
        msg: "Docker service status: {{ ansible_facts.services['docker.service'].state }}"

    - name: Show UFW status
      ansible.builtin.debug:
        msg: "UFW service status: {{ ansible_facts.services['ufw.service'].state }}"

    - name: Show Fail2ban status
      ansible.builtin.debug:
        msg: "Fail2ban service status: {{ ansible_facts.services['fail2ban.service'].state }}"
