---
- name: Test Monitoring Role Handlers
  hosts: all
  gather_facts: false
  tasks:
    - name: Test handler file exists
      ansible.builtin.stat:
        path: "{{ role_path }}/handlers/main.yml"
      register: handler_file
      delegate_to: localhost

    - name: Fail if handler file missing
      ansible.builtin.fail:
        msg: "Handler file missing: {{ role_path }}/handlers/main.yml"
      when: not handler_file.stat.exists
      delegate_to: localhost

    - name: Validate handler file syntax
      ansible.builtin.command: ansible-lint "{{ role_path }}/handlers/main.yml"
      register: lint_result
      delegate_to: localhost
      ignore_errors: true

    - name: Display handler validation result
      ansible.builtin.debug:
        msg: "Handler validation {{ 'PASSED' if lint_result.rc == 0 else 'FAILED' }}"
      delegate_to: localhost

    - name: List available handlers
      ansible.builtin.debug:
        msg: "Available handlers in monitoring role"
      delegate_to: localhost 