---
- name: Validate core system variables
  ansible.builtin.fail:
    msg: "CRITICAL: Required variable '{{ item }}' is not defined. Please set it in inventory/group_vars/all/main.yml or secrets/vault.yml"
  when: item is not defined
  loop:
    - vault_vps_server_ip
    - vault_initial_deployment_user
    - vault_initial_deployment_ssh_key
    - vault_containers_deployment_user
    - vault_containers_deployment_user_ssh_key
    - vault_containers_deployment_user_ssh_key_public

- name: Validate email configuration variables
  ansible.builtin.fail:
    msg: "CRITICAL: Required email variable '{{ item }}' is not defined. Please set it in secrets/vault.yml"
  when: item is not defined
  loop:
    - vault_configure_security_updates_email
    - vault_configure_security_updates_gmail_user
    - vault_configure_security_updates_gmail_password
    - vault_configure_monitoring_alert_email
    - vault_configure_reporting_email
    - vault_configure_reporting_gmail_user
    - vault_configure_reporting_gmail_password
    - vault_configure_container_security_alert_email

- name: Validate SMTP configuration variables
  ansible.builtin.fail:
    msg: "CRITICAL: Required SMTP variable '{{ item }}' is not defined. Please set it in secrets/vault.yml"
  when: item is not defined
  loop:
    - vault_configure_security_updates_gmail_smtp_server
    - vault_configure_security_updates_gmail_smtp_port
    - vault_configure_reporting_gmail_smtp_server
    - vault_configure_reporting_gmail_smtp_port

- name: Validate remote logging configuration
  ansible.builtin.fail:
    msg: "CRITICAL: Required remote logging variable '{{ item }}' is not defined. Please set it in secrets/vault.yml"
  when: item is not defined
  loop:
    - vault_configure_remote_logging_server

- name: Validate webhook configuration (optional but check if defined)
  ansible.builtin.debug:
    msg: "WARNING: Optional webhook variable '{{ item }}' is not defined. This is OK if you don't use webhooks."
  when: item is not defined
  loop:
    - vault_configure_security_updates_slack_webhook
    - vault_configure_security_updates_discord_webhook
    - vault_configure_monitoring_alert_webhook

- name: Validate daily retention variable
  ansible.builtin.fail:
    msg: "CRITICAL: configure_reporting_daily_retention_days is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: configure_reporting_daily_retention_days is not defined

- name: Validate weekly retention variable
  ansible.builtin.fail:
    msg: "CRITICAL: configure_reporting_weekly_retention_days is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: configure_reporting_weekly_retention_days is not defined

- name: Validate monthly retention variable
  ansible.builtin.fail:
    msg: "CRITICAL: configure_reporting_monthly_retention_days is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: configure_reporting_monthly_retention_days is not defined

- name: Validate features.containers.networks.remove_all
  ansible.builtin.fail:
    msg: "CRITICAL: features.containers.networks.remove_all is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: features.containers.networks.remove_all is not defined

- name: Validate features.containers.networks.test_mode
  ansible.builtin.fail:
    msg: "CRITICAL: features.containers.networks.test_mode is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: features.containers.networks.test_mode is not defined

- name: Validate configure_docker_networks_default_driver
  ansible.builtin.fail:
    msg: "CRITICAL: configure_docker_networks_default_driver is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: configure_docker_networks_default_driver is not defined

- name: Validate configure_monitoring_alerts_email
  ansible.builtin.fail:
    msg: "CRITICAL: configure_monitoring_alerts_email is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: configure_monitoring_alerts_email is not defined

- name: Validate configure_monitoring_alerts_slack_webhook
  ansible.builtin.fail:
    msg: "CRITICAL: configure_monitoring_alerts_slack_webhook is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: configure_monitoring_alerts_slack_webhook is not defined

- name: Debug - Show all features variables
  ansible.builtin.debug:
    msg: "Features: {{ features | default('UNDEFINED') }}"

- name: Debug - Show features.monitoring specifically
  ansible.builtin.debug:
    msg: "features.monitoring: {{ features.monitoring | default('UNDEFINED') }}"

- name: Validate features.monitoring
  ansible.builtin.fail:
    msg: "CRITICAL: features.monitoring is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: features.monitoring is not defined

- name: Validate monitoring.core.health_check_interval
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.core.health_check_interval is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.core.health_check_interval is not defined

- name: Validate monitoring.core.disk_threshold
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.core.disk_threshold is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.core.disk_threshold is not defined

- name: Validate monitoring.core.memory_threshold
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.core.memory_threshold is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.core.memory_threshold is not defined

- name: Validate monitoring.core.cpu_threshold
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.core.cpu_threshold is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.core.cpu_threshold is not defined

- name: Validate monitoring.core.network_threshold
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.core.network_threshold is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.core.network_threshold is not defined

- name: Validate monitoring.resources.memory_limit
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.resources.memory_limit is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.resources.memory_limit is not defined

- name: Validate monitoring.resources.cpu_limit
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.resources.cpu_limit is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.resources.cpu_limit is not defined

- name: Validate monitoring.resources.log_retention_days
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.resources.log_retention_days is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.resources.log_retention_days is not defined

- name: Validate monitoring.resources.max_log_size
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.resources.max_log_size is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.resources.max_log_size is not defined

- name: Validate monitoring.docker.logs_enabled
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.docker.logs_enabled is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.docker.logs_enabled is not defined

- name: Validate monitoring.docker.log_driver
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.docker.log_driver is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.docker.log_driver is not defined

- name: Validate monitoring.docker.log_max_size
  ansible.builtin.fail:
    msg: "CRITICAL: monitoring.docker.log_max_size is not defined. Please set it in inventory/group_vars/all/main.yml"
  when: monitoring.docker.log_max_size is not defined

- name: Display validation success
  ansible.builtin.debug:
    msg: "All required variables are properly defined! Proceeding with deployment..."

- name: Show configuration summary
  ansible.builtin.debug:
    msg: |
      Configuration Summary:
      • Server: {{ vault_vps_server_ip }}
      • Email: {{ vault_configure_reporting_email }}
      • Monitoring: {{ configure_monitoring_enabled }}
      • Reporting: {{ configure_reporting_enabled }}
      • Container Security: {{ configure_container_security_enabled }}
      • Docker Networks: {{ configure_docker_networks_default_networks | length }} networks configured
