---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ configure_security_updates_packages }}"
    state: present
    update_cache: true
  become: true

- name: Create security updates script directory
  ansible.builtin.file:
    path: "{{ configure_security_updates_script_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Create enhanced notification script
  ansible.builtin.template:
    src: security-update-notify.sh.j2
    dest: "{{ configure_security_updates_notification_script }}"
    mode: "{{ configure_security_updates_notification_script_permissions }}"
    owner: root
    group: root
  become: true
  notify: Restart security updates service

- name: Configure unattended upgrades with enhanced error handling
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    owner: root
    group: root
  become: true
  notify: Restart unattended upgrades

- name: Configure enhanced unattended upgrades settings
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"
    owner: root
    group: root
  become: true
  notify: Restart unattended upgrades

- name: Create enhanced error handling script
  ansible.builtin.template:
    src: unattended-upgrade-error-handler.sh.j2
    dest: /usr/local/bin/unattended-upgrade-error-handler.sh
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Create log file
  ansible.builtin.file:
    path: "{{ configure_security_updates_log_file }}"
    state: touch
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Configure logrotate for security updates
  ansible.builtin.template:
    src: security-updates.j2
    dest: /etc/logrotate.d/security-updates
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Create cron job for repository health check
  ansible.builtin.cron:
    name: "Repository Health Check"
    hour: "1"
    minute: "30"
    job: "/usr/local/bin/unattended-upgrade-error-handler.sh"
    user: root
  become: true

- name: Test notification script
  ansible.builtin.command: "{{ configure_security_updates_notification_script }} 'Test Notification' 'Security updates configuration test'"
  become: true
  changed_when: false
  failed_when: false

- name: Create error state file
  ansible.builtin.file:
    path: /var/log/unattended-upgrade-errors.state
    state: touch
    mode: "0644"
    owner: root
    group: root
  become: true
