---
# Docker deployment behavior settings
deploy_docker_security_enabled: true

# Package configuration (Behavior)
deploy_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

# Docker network configuration (use variables from all.yml)
deploy_docker_network_configuration: "{{ deploy_docker_network_configuration | default({}) }}"

# Container network policies (use variables from all.yml)
deploy_docker_network_policies: "{{ deploy_docker_network_policies | default({}) }}"
